# Introduction to PyTorch

### How to run the code

#### Option 1: Running using free online resources (1-click, recommended)

The easiest way to start executing the code is to run it on Google Colab by simply downloading this file and uploading it on Google Colab.


#### Option 2: Running on your computer locally

To run the code on your computer locally, you'll need to set up [Python](https://www.python.org), download the notebook and install the required libraries. We recommend using the [Conda](https://docs.conda.io/projects/conda/en/latest/user-guide/install/) distribution of Python. 

>  **Jupyter Notebooks**: This tutorial is a [Jupyter notebook](https://jupyter.org) - a document made of _cells_. Each cell can contain code written in Python or explanations in plain English. You can execute code cells and view the results, e.g., numbers, messages, graphs, tables, files, etc. instantly within the notebook. Jupyter is a powerful platform for experimentation and analysis. Don't be afraid to mess around with the code & break things - you'll learn a lot by encountering and fixing errors. You can use the "Kernel > Restart & Clear Output" or "Edit > Clear Outputs" menu option to clear all outputs and start again from the top.

Before we begin, we need to install the required libraries. The installation of PyTorch may differ based on your operating system / cloud environment. You can find detailed installation instructions here: https://pytorch.org .


In [3]:
# Uncomment and run the appropriate command for your operating system, if required

# Linux / Binder
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# Windows
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# MacOS
# !pip install numpy torch torchvision torchaudio

Let's import the torch module to get started

In [4]:
import torch

## Tensors

At its core, PyTorch is a library for processing tensors. 

A torch.Tensor is a multi-dimensional matrix containing elements of a single data type.

Torch defines 10 tensor types with CPU and GPU variants which can be found on it's offcial [documentation page](https://pytorch.org/docs/stable/tensors.html)

In [5]:
# Number
t1 = torch.tensor(4.)
t1

tensor(4.)

In [6]:
# Vector
t2 = torch.tensor([1., 2, 3, 4])
t2

tensor([1., 2., 3., 4.])

In [7]:
# Matrix
t3 = torch.tensor([[5., 6], 
                   [7, 8], 
                   [9, 10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [8]:
# 3-dimensional array
t4 = torch.tensor([
    [[11, 12, 13], 
     [13, 14, 15]], 
    [[15, 16, 17], 
     [17, 18, 19.]]])
t4

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])

The contents of a tensor can be accessed and modified using Python’s indexing and slicing notation:

In [9]:
t5 = torch.tensor([[1,2,3],
                   [4,5,6]])
t5[0,1]

tensor(2)

In [10]:
t5[1,2]=0
t5

tensor([[1, 2, 3],
        [4, 5, 0]])

Tensors can have any number of dimensions and different lengths along each dimension. We can inspect the length along each dimension using the `.shape` property of a tensor.

In [11]:
print(t1)
t1.shape

tensor(4.)


torch.Size([])

In [12]:
print(t2)
t2.shape

tensor([1., 2., 3., 4.])


torch.Size([4])

In [13]:
print(t3)
t3.shape

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])


torch.Size([3, 2])

In [14]:
print(t4)
t4.shape

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])


torch.Size([2, 2, 3])

In [15]:
print(t5)
t5.shape

tensor([[1, 2, 3],
        [4, 5, 0]])


torch.Size([2, 3])

Note that it's not possible to create tensors with an improper shape.

In [16]:
# Matrix
t6 = torch.tensor([[5., 6, 11], 
                   [7, 8], 
                   [9, 10]])
t6

ValueError: ignored

### Tensor operations and gradients

We can combine tensors with the usual arithmetic operations. Let's look at an example:

In [17]:
x = torch.tensor(2.)
y = torch.tensor(5., requires_grad=True)
z = torch.tensor(7., requires_grad=True)

We have creates 3 tensors `x`,`y` and `z` with 2 of them having gradient set to `True`

In [18]:
#Arithmetic Operation
f = x * y + z
f

tensor(17., grad_fn=<AddBackward0>)

What makes PyTorch unique is that we can automatically compute the derivative of `f` w.r.t. the tensors that have `requires_grad` set to `True` i.e. w and b. This feature of PyTorch is called [_autograd_](https://pytorch.org/docs/stable/autograd.html#module-torch.autograd) (automatic gradients).

To compute the derivatives, we can invoke the `.backward` method on our result `y`.


In [19]:
# Compute derivatives
f.backward()

The derivatives of `f` with respect to the input tensors are stored in the `.grad` property of the respective tensors.

In [20]:
# Display gradients
print('df/dx:', x.grad)
print('df/dy:', y.grad)
print('df/dz:', z.grad)

df/dx: None
df/dy: tensor(2.)
df/dz: tensor(1.)


### Tensor functions

Apart from arithmetic operations, the `torch` module also contains many functions for creating and manipulating tensors. Let's look at some examples.

In [21]:
# Create a tensor with a fixed value for every element
t7 = torch.full((3, 2), 31)
t7

tensor([[31, 31],
        [31, 31],
        [31, 31]])

In [25]:
# Concatenate two tensors with compatible shapes
t8 = torch.cat((t3, t7))
t8

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [31., 31.],
        [31., 31.],
        [31., 31.]])

In [26]:
# Compute the cos of each element
t9 = torch.cos(t8)
t9

tensor([[ 0.2837,  0.9602],
        [ 0.7539, -0.1455],
        [-0.9111, -0.8391],
        [ 0.9147,  0.9147],
        [ 0.9147,  0.9147],
        [ 0.9147,  0.9147]])

In [32]:
# Change the shape of a tensor
t10 = t9.reshape(3, 2, 2)
t10

tensor([[[ 0.2837,  0.9602],
         [ 0.7539, -0.1455]],

        [[-0.9111, -0.8391],
         [ 0.9147,  0.9147]],

        [[ 0.9147,  0.9147],
         [ 0.9147,  0.9147]]])

Let's look at difference between 2 very similar functions:

In [35]:
#Difference between 2 PyTorch Functions:  view & permute

x = torch.rand(2,4) #generates a random tensor of 2x4

print('x:', x)

print('shape:', x.shape)



y = x.view(4, 2) #view the tensor as 4x2

print('y:', y)

print('shape:', y.shape)



z = x.permute(1, 0) #works like transpose of a matrix

print('z:', z)

print('shape:', z.shape)

x: tensor([[0.1001, 0.1410, 0.9418, 0.5167],
        [0.6634, 0.4888, 0.3876, 0.4063]])
shape: torch.Size([2, 4])
y: tensor([[0.1001, 0.1410],
        [0.9418, 0.5167],
        [0.6634, 0.4888],
        [0.3876, 0.4063]])
shape: torch.Size([4, 2])
z: tensor([[0.1001, 0.6634],
        [0.1410, 0.4888],
        [0.9418, 0.3876],
        [0.5167, 0.4063]])
shape: torch.Size([4, 2])


You can find more useful functions in the official documentation [here](https://pytorch.org/docs/stable/torch.html)

## Interoperability with Numpy

[Numpy](http://www.numpy.org/) is a popular open-source library used for mathematical and scientific computing in Python. It enables efficient operations on large multi-dimensional arrays and has a vast ecosystem of supporting libraries, including:

* [Pandas](https://pandas.pydata.org/) for file I/O and data analysis
* [Matplotlib](https://matplotlib.org/) for plotting and visualization
* [OpenCV](https://opencv.org/) for image and video processing

Instead of reinventing the wheel, PyTorch interoperates well with Numpy to leverage its existing ecosystem of tools and libraries.

In [28]:
import numpy as np

x = np.array([[1, 2], [3, 4.]])
x

array([[1., 2.],
       [3., 4.]])

We can convert a Numpy array to a PyTorch tensor using `torch.from_numpy`.

In [29]:
# Convert the numpy array to a torch tensor.
y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

Numpy array and Torch tensor will have similar datatype:

In [30]:
x.dtype, y.dtype

(dtype('float64'), torch.float64)

We can convert a PyTorch tensor to a Numpy array using the `.numpy` method of a tensor.

In [31]:
# Convert a torch tensor to a numpy array
z = y.numpy()
z

array([[1., 2.],
       [3., 4.]])

The interoperability between PyTorch and Numpy is essential because most datasets you'll work with will likely be read and preprocessed as Numpy arrays.


### But why do we even need Pytorch? 

You might wonder why we need a library like PyTorch at all since Numpy already provides data structures and utilities for working with multi-dimensional numeric data. There are two main reasons:

1. **Autograd**: The ability to automatically compute gradients for tensor operations is essential for training deep learning models.
2. **GPU support**: While working with massive datasets and large models, PyTorch tensor operations can be performed efficiently using a Graphics Processing Unit (GPU). Computations that might typically take hours can be completed within minutes using GPUs.
